hw07_file_copying
Nickolas990/otus_hw pull request #7
Opened 2024-11-09 11:54 UTC by Nickolas990

## Домашнее задание №7 «Утилита для копирования файлов»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я провел ручное тестирование программы (например, запускал `test.sh`).

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2024-11-09 17:48 UTC, vladislavmass requested changes

2024-11-09 17:48 UTC, vladislavmass commented on hw07_file_copying/copy.go
> +	if fileInfo.Size() < offset {
А чем эта проверка отличается от проверки в 36 строке?

2024-11-09 17:48 UTC, vladislavmass commented on hw07_file_copying/copy.go
> +	destFile, err := os.Create(toPath)
Если src и dst совпадут то после этой строчки содержимое файла будет потеряно

2024-11-09 18:14 UTC, Nickolas990 commented on hw07_file_copying/copy.go
> +	if fileInfo.Size() < offset {
Задублировал случайно, когда из гит-лога вытаскивал. Убрал.

2024-11-09 18:14 UTC, Nickolas990 commented on hw07_file_copying/copy.go
> +	destFile, err := os.Create(toPath)
Перенес проверку до Create

2024-11-10 04:49 UTC, vladislavmass approved these changes

2024-11-10 09:59 UTC, merged